import type { ConversionField } from '../types/conversion.types'

/**
 * Catálogo de campos de conversão expostos ao frontend via GET /options.
 *
 * NOTA: kccFlag e kccMap são mapeados internamente em kcc-flag-mapper.ts
 * e NUNCA são expostos ao frontend.
 */
export const fields: ConversionField[] = [
  // ── Reading ─────────────────────────────────────────────────────
  {
    id: 'mangaMode',
    type: 'boolean',
    component: 'switch',
    label: 'Modo Mangá',
    description: 'Ativa leitura no estilo mangá (da direita para a esquerda).',
    help: 'Inverte a ordem das páginas e o sentido de leitura.',
    default: false,
    group: 'reading',
  },
  {
    id: 'webtoonMode',
    type: 'boolean',
    component: 'switch',
    label: 'Modo Webtoon',
    description: 'Processamento otimizado para tiras longas verticais.',
    help: 'Mantém a ordem vertical original sem dividir em páginas.',
    default: false,
    group: 'reading',
  },
  {
    id: 'invertDirection',
    type: 'boolean',
    component: 'switch',
    label: 'Inverter Direção',
    description: 'Inverte a direção de leitura das páginas.',
    help: 'Útil para obras ocidentais em modo mangá.',
    default: false,
    group: 'reading',
  },
  {
    id: 'lightnovel',
    type: 'boolean',
    component: 'switch',
    label: 'Light Novel',
    description: 'Otimiza para light novels com texto e imagens.',
    help: 'Preserva a formatação de texto e imagens em preto e branco.',
    default: false,
    group: 'reading',
  },
  {
    id: 'twoPanel',
    type: 'boolean',
    component: 'switch',
    label: '2 Painéis',
    description: 'Divide páginas de 2 painéis em páginas separadas.',
    help: 'Útil para quadrinhos ocidentais com formato de página dupla.',
    default: false,
    group: 'reading',
  },
  {
    id: 'vertical4Panel',
    type: 'boolean',
    component: 'switch',
    label: '4 Painéis Verticais',
    description: 'Otimiza para tiras de 4 painéis (formato yonkoma).',
    help: 'Comum em mangás de comédia com formato 4-koma.',
    default: false,
    group: 'reading',
  },

  // ── Processing ──────────────────────────────────────────────────
  {
    id: 'highQuality',
    type: 'boolean',
    component: 'switch',
    label: 'Alta Qualidade',
    description: 'Usa algoritmos de redimensionamento de maior qualidade.',
    help: 'Mais lento, mas produz imagens mais nítidas.',
    default: false,
    group: 'processing',
  },
  {
    id: 'noProcessing',
    type: 'boolean',
    component: 'switch',
    label: 'Sem Processamento',
    description: 'Converte sem otimizar ou redimensionar imagens.',
    help: 'Ignora todos os outros campos de processamento quando ativo.',
    default: false,
    group: 'processing',
  },
  {
    id: 'stretchMode',
    type: 'enum',
    component: 'select',
    label: 'Redimensionamento',
    description: 'Como redimensionar imagens que não cabem na tela.',
    help: 'Upscale aumenta sem deformar. Esticar preenche a tela. Desabilitado mantém original.',
    default: 'disabled',
    group: 'processing',
    options: [
      { id: 'disabled', label: 'Desabilitado' },
      { id: 'stretch', label: 'Esticar' },
      { id: 'upscale', label: 'Upscale' },
    ],
  },
  {
    id: 'splitter',
    type: 'enum',
    component: 'select',
    label: 'Páginas Duplas',
    description: 'Como tratar páginas duplas (spreads) encontradas no mangá.',
    help: 'Dividir separa em duas imagens. Rotacionar gira 90° para paisagem.',
    default: 'split',
    group: 'processing',
    options: [
      { id: 'split', label: 'Dividir' },
      { id: 'rotate', label: 'Rotacionar' },
      { id: 'both', label: 'Dividir e Rotacionar' },
    ],
  },
  {
    id: 'cropping',
    type: 'enum',
    component: 'select',
    label: 'Recorte',
    description: 'Nível de recorte automático das bordas.',
    help: 'Margens remove bordas brancas. Números de página também remove numeração.',
    default: 'marginsAndPageNumbers',
    group: 'processing',
    options: [
      { id: 'disabled', label: 'Desabilitado' },
      { id: 'margins', label: 'Apenas Margens' },
      { id: 'marginsAndPageNumbers', label: 'Margens e Números' },
    ],
  },
  {
    id: 'interPanelCrop',
    type: 'enum',
    component: 'select',
    label: 'Recorte Entre Painéis',
    description: 'Recorta espaços entre painéis para maximizar área de leitura.',
    help: 'Horizontal recorta apenas laterais. Ambos recorta vertical e horizontal.',
    default: 'disabled',
    group: 'processing',
    options: [
      { id: 'disabled', label: 'Desabilitado' },
      { id: 'horizontal', label: 'Horizontal' },
      { id: 'both', label: 'Ambos' },
    ],
  },
  // batchSplit é interno do Planner (não exposto na API pública)
  {
    id: 'maximizeStrips',
    type: 'boolean',
    component: 'switch',
    label: 'Maximizar Tiras',
    description: 'Maximiza tiras verticais unindo páginas.',
    help: 'Útil para webtoons com tiras curtas.',
    default: false,
    group: 'processing',
  },
  {
    id: 'legacyExtract',
    type: 'boolean',
    component: 'switch',
    label: 'Extração Legada',
    description: 'Usa método de extração legado para arquivos ZIP.',
    help: 'Apenas se o método padrão falhar.',
    default: false,
    group: 'processing',
  },

  // ── Image ───────────────────────────────────────────────────────
  {
    id: 'gamma',
    type: 'number',
    component: 'slider',
    label: 'Gamma',
    description: 'Ajuste de gamma para correção de brilho/contraste.',
    help: 'Valores >1 clareiam, <1 escurecem. Auto deixa o KCC decidir.',
    default: 'auto',
    group: 'image',
    min: 0.1,
    max: 5.0,
    step: 0.1,
  },
  {
    id: 'jpegQuality',
    type: 'number',
    component: 'slider',
    label: 'Qualidade JPEG',
    description: 'Qualidade de compressão JPEG para as imagens de saída.',
    help: 'Valores mais altos = maior qualidade, arquivo maior.',
    default: 85,
    group: 'image',
    min: 0,
    max: 95,
    step: 1,
  },
  {
    id: 'forceColor',
    type: 'boolean',
    component: 'switch',
    label: 'Manter Cores',
    description: 'Preserva as cores originais em vez de converter para tons de cinza.',
    help: 'Útil para obras coloridas. Arquivo resultante será maior.',
    default: false,
    group: 'image',
  },
  {
    id: 'eraseRainbow',
    type: 'boolean',
    component: 'switch',
    label: 'Apagar Efeito Arco-íris',
    description: 'Remove artefatos de cor em bordas de texto preto.',
    help: 'Comum em scans de baixa qualidade com compressão JPEG agressiva.',
    default: false,
    group: 'image',
  },
  {
    id: 'noQuantize',
    type: 'boolean',
    component: 'switch',
    label: 'Sem Quantização',
    description: 'Desabilita quantização de cores (preserva paleta original).',
    help: 'Útil para obras com gradientes suaves.',
    default: false,
    group: 'image',
  },
  {
    id: 'noAutocontrast',
    type: 'boolean',
    component: 'switch',
    label: 'Sem Autocontraste',
    description: 'Desabilita correção automática de contraste.',
    help: 'Ative se o autocontraste estiver deixando as imagens muito escuras.',
    default: false,
    group: 'image',
  },
  {
    id: 'autolevel',
    type: 'boolean',
    component: 'switch',
    label: 'Nível Automático',
    description: 'Ajusta níveis de cor automaticamente.',
    help: 'Melhora contraste geral da imagem.',
    default: false,
    group: 'image',
  },
  {
    id: 'colorAutocontrast',
    type: 'boolean',
    component: 'switch',
    label: 'Autocontraste Colorido',
    description: 'Aplica autocontraste preservando cores.',
    help: 'Como o autocontraste normal, mas mantém informações de cor.',
    default: false,
    group: 'image',
  },
  {
    id: 'blackBorders',
    type: 'boolean',
    component: 'switch',
    label: 'Bordas Pretas',
    description: 'Adiciona bordas pretas ao redor das páginas.',
    help: 'Útil para obras com margens irregulares.',
    default: false,
    group: 'image',
  },
  {
    id: 'whiteBorders',
    type: 'boolean',
    component: 'switch',
    label: 'Bordas Brancas',
    description: 'Adiciona bordas brancas ao redor das páginas.',
    help: 'Alternativa às bordas pretas para fundos escuros.',
    default: false,
    group: 'image',
  },
  {
    id: 'forcePng',
    type: 'boolean',
    component: 'switch',
    label: 'Forçar PNG',
    description: 'Força o uso de PNG para todas as imagens de saída.',
    help: 'Maior qualidade, arquivo maior. Útil para obras com texto.',
    default: false,
    group: 'image',
  },
  {
    id: 'webp',
    type: 'boolean',
    component: 'switch',
    label: 'WebP',
    description: 'Usa formato WebP para compressão de imagens.',
    help: 'Melhor compressão que JPEG com qualidade similar.',
    default: false,
    group: 'image',
  },
  {
    id: 'mozjpeg',
    type: 'boolean',
    component: 'switch',
    label: 'MozJPEG',
    description: 'Usa encoder MozJPEG para compressão JPEG.',
    help: 'Melhor qualidade que JPEG padrão no mesmo tamanho.',
    default: false,
    group: 'image',
  },
  {
    id: 'croppingPower',
    type: 'number',
    component: 'slider',
    label: 'Poder de Recorte',
    description: 'Intensidade do algoritmo de recorte de bordas.',
    help: 'Valores mais altos recortam mais agressivamente.',
    default: 1.0,
    group: 'image',
    min: 0.1,
    max: 2.0,
    step: 0.1,
  },
  {
    id: 'croppingMinimum',
    type: 'number',
    component: 'slider',
    label: 'Mínimo de Recorte',
    description: 'Recorte mínimo aplicado antes do algoritmo adaptativo.',
    help: 'Útil para obras com margens consistentes.',
    default: 0.0,
    group: 'image',
    min: 0.0,
    max: 1.0,
    step: 0.05,
  },

  // ── Output ──────────────────────────────────────────────────────
  {
    id: 'metadataTitle',
    type: 'enum',
    component: 'select',
    label: 'Título dos Metadados',
    description: 'Como tratar o título nos metadados do arquivo de saída.',
    help: 'Combinar junta com nome do arquivo. Apenas metadados não altera nome.',
    default: 'ignore',
    group: 'output',
    options: [
      { id: 'ignore', label: 'Ignorar' },
      { id: 'combine', label: 'Combinar' },
      { id: 'metadataOnly', label: 'Apenas Metadados' },
    ],
  },
  {
    id: 'noRotate',
    type: 'boolean',
    component: 'switch',
    label: 'Não Rotacionar',
    description: 'Desabilita rotação automática de páginas.',
    help: 'Útil se o KCC estiver rotacionando páginas incorretamente.',
    default: false,
    group: 'output',
  },
  {
    id: 'rotateRight',
    type: 'boolean',
    component: 'switch',
    label: 'Rotacionar à Direita',
    description: 'Rotaciona todas as páginas 90° à direita.',
    help: 'Útil para obras em formato paisagem.',
    default: false,
    group: 'output',
  },
  {
    id: 'rotateFirst',
    type: 'boolean',
    component: 'switch',
    label: 'Rotacionar Primeiro',
    description: 'Rotaciona antes de qualquer outro processamento.',
    help: 'Útil quando a rotação precisa ser aplicada antes do recorte.',
    default: false,
    group: 'output',
  },
  {
    id: 'coverFill',
    type: 'boolean',
    component: 'switch',
    label: 'Capa Preencher Tela',
    description: 'Estica a capa para preencher a tela inteira.',
    help: 'Evita bordas ao redor da imagem de capa.',
    default: false,
    group: 'output',
  },
  {
    id: 'smartCoverCrop',
    type: 'boolean',
    component: 'switch',
    label: 'Recorte Inteligente da Capa',
    description: 'Recorta a capa automaticamente para preencher a tela.',
    help: 'Mais inteligente que simplesmente esticar.',
    default: false,
    group: 'output',
  },
  {
    id: 'onePageLandscape',
    type: 'boolean',
    component: 'switch',
    label: '1 Página Paisagem',
    description: 'Trata páginas paisagem como uma página única.',
    help: 'Evita dividir páginas largas em duas telas.',
    default: false,
    group: 'output',
  },
  // fileFusion é interno do Planner (não exposto na API pública)
  {
    id: 'spreadShift',
    type: 'boolean',
    component: 'switch',
    label: 'Deslocar Spread',
    description: 'Ajusta spreads para compensar encadernação.',
    help: 'Útil para scanners que não centralizaram o spread.',
    default: false,
    group: 'output',
  },
  {
    id: 'preserveMargin',
    type: 'boolean',
    component: 'switch',
    label: 'Preservar Margem',
    description: 'Preserva margens durante o processamento.',
    help: 'Útil quando as margens contêm informação relevante.',
    default: false,
    group: 'output',
  },
  {
    id: 'nokepub',
    type: 'boolean',
    component: 'switch',
    label: 'Sem KEPUB',
    description: 'Desabilita geração de formato KEPUB da Kobo.',
    help: 'Apenas relevante para dispositivos Kobo.',
    default: false,
    group: 'format',
  },
  {
    id: 'customWidth',
    type: 'number',
    component: 'input',
    label: 'Largura Customizada',
    description: 'Largura personalizada em pixels para a saída.',
    help: 'Substitui a resolução do dispositivo selecionado.',
    default: 0,
    group: 'output',
    min: 100,
    max: 9999,
    step: 1,
  },
  {
    id: 'customHeight',
    type: 'number',
    component: 'input',
    label: 'Altura Customizada',
    description: 'Altura personalizada em pixels para a saída.',
    help: 'Substitui a resolução do dispositivo selecionado.',
    default: 0,
    group: 'output',
    min: 100,
    max: 9999,
    step: 1,
  },
  {
    id: 'targetSize',
    type: 'number',
    component: 'input',
    label: 'Tamanho Alvo (MB)',
    description: 'Tamanho alvo aproximado do arquivo de saída em MB.',
    help: 'KCC tentará ajustar compressão para atingir este tamanho.',
    default: 0,
    group: 'output',
    min: 1,
    max: 100,
    step: 1,
  },
]