export { ProviderResolver } from './provider-resolver'
export { MangaLivreStrategy } from './mangalivre/mangalivre.provider'
export { ImperioDaBritanniaStrategy } from './imperiodabritannia/imperiodabritannia.provider'
export { MangaDexStrategy } from './mangadex/mangadex.provider'
export { TaiyoStrategy } from './taiyo/taiyo.provider'
export { MangapillStrategy } from './mangapill/mangapill.provider'
export { MangaReadStrategy } from './mangaread/mangaread.provider'
export { FlameComicsStrategy, FlameComicsProvider } from './flamecomics/flamecomics.provider'
export { AsuraScansProvider, AsuraScansProvider as AsuraScansStrategy } from './asurascans/asurascans.provider'
export { MangaKakalotStrategy } from './mangakakalot/mangakakalot.provider'
export { MangaFireStrategy } from './mangafire/mangafire.provider'
export type { IProviderStrategy } from '../interfaces/provider-strategy.interface'
export type { ScrapingProvider } from './provider.interface'
