/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as BibliotecaSlugRouteImport } from './routes/biblioteca.$slug'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaSlugRoute = BibliotecaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibliotecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca': typeof BibliotecaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/biblioteca'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/wizard'
    | '/biblioteca/$slug'
    | '/biblioteca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/wizard'
    | '/biblioteca/$slug'
    | '/biblioteca'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/biblioteca'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/wizard'
    | '/biblioteca/$slug'
    | '/biblioteca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FontesRoute: typeof FontesRoute
  LoginRoute: typeof LoginRoute
  WizardRoute: typeof WizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/$slug': {
      id: '/biblioteca/$slug'
      path: '/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof BibliotecaSlugRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaSlugRoute: typeof BibliotecaSlugRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaSlugRoute: BibliotecaSlugRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FontesRoute: FontesRoute,
  LoginRoute: LoginRoute,
  WizardRoute: WizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
