/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as BibliotecaProgressoRouteImport } from './routes/biblioteca.progresso'
import { Route as BibliotecaSourceIdRouteImport } from './routes/biblioteca.$sourceId'
import { Route as BibliotecaReaderConversionIdRouteImport } from './routes/biblioteca.reader.$conversionId'
import { Route as BibliotecaReaderChapterSourceIdRouteImport } from './routes/biblioteca.reader-chapter.$sourceId'
import { Route as BibliotecaConverterJobIdRouteImport } from './routes/biblioteca.converter.$jobId'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaProgressoRoute = BibliotecaProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaSourceIdRoute = BibliotecaSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaReaderConversionIdRoute =
  BibliotecaReaderConversionIdRouteImport.update({
    id: '/reader/$conversionId',
    path: '/reader/$conversionId',
    getParentRoute: () => BibliotecaRoute,
  } as any)
const BibliotecaReaderChapterSourceIdRoute =
  BibliotecaReaderChapterSourceIdRouteImport.update({
    id: '/reader-chapter/$sourceId',
    path: '/reader-chapter/$sourceId',
    getParentRoute: () => BibliotecaRoute,
  } as any)
const BibliotecaConverterJobIdRoute =
  BibliotecaConverterJobIdRouteImport.update({
    id: '/converter/$jobId',
    path: '/converter/$jobId',
    getParentRoute: () => BibliotecaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$sourceId': typeof BibliotecaSourceIdRoute
  '/biblioteca/progresso': typeof BibliotecaProgressoRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/converter/$jobId': typeof BibliotecaConverterJobIdRoute
  '/biblioteca/reader-chapter/$sourceId': typeof BibliotecaReaderChapterSourceIdRoute
  '/biblioteca/reader/$conversionId': typeof BibliotecaReaderConversionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$sourceId': typeof BibliotecaSourceIdRoute
  '/biblioteca/progresso': typeof BibliotecaProgressoRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/biblioteca/converter/$jobId': typeof BibliotecaConverterJobIdRoute
  '/biblioteca/reader-chapter/$sourceId': typeof BibliotecaReaderChapterSourceIdRoute
  '/biblioteca/reader/$conversionId': typeof BibliotecaReaderConversionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/wizard': typeof WizardRoute
  '/biblioteca/$sourceId': typeof BibliotecaSourceIdRoute
  '/biblioteca/progresso': typeof BibliotecaProgressoRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/converter/$jobId': typeof BibliotecaConverterJobIdRoute
  '/biblioteca/reader-chapter/$sourceId': typeof BibliotecaReaderChapterSourceIdRoute
  '/biblioteca/reader/$conversionId': typeof BibliotecaReaderConversionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/biblioteca'
    | '/cadastro'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/perfil'
    | '/wizard'
    | '/biblioteca/$sourceId'
    | '/biblioteca/progresso'
    | '/biblioteca/'
    | '/biblioteca/converter/$jobId'
    | '/biblioteca/reader-chapter/$sourceId'
    | '/biblioteca/reader/$conversionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/cadastro'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/perfil'
    | '/wizard'
    | '/biblioteca/$sourceId'
    | '/biblioteca/progresso'
    | '/biblioteca'
    | '/biblioteca/converter/$jobId'
    | '/biblioteca/reader-chapter/$sourceId'
    | '/biblioteca/reader/$conversionId'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/biblioteca'
    | '/cadastro'
    | '/configuracoes'
    | '/fontes'
    | '/login'
    | '/perfil'
    | '/wizard'
    | '/biblioteca/$sourceId'
    | '/biblioteca/progresso'
    | '/biblioteca/'
    | '/biblioteca/converter/$jobId'
    | '/biblioteca/reader-chapter/$sourceId'
    | '/biblioteca/reader/$conversionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FontesRoute: typeof FontesRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  WizardRoute: typeof WizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/progresso': {
      id: '/biblioteca/progresso'
      path: '/progresso'
      fullPath: '/biblioteca/progresso'
      preLoaderRoute: typeof BibliotecaProgressoRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/$sourceId': {
      id: '/biblioteca/$sourceId'
      path: '/$sourceId'
      fullPath: '/biblioteca/$sourceId'
      preLoaderRoute: typeof BibliotecaSourceIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/reader/$conversionId': {
      id: '/biblioteca/reader/$conversionId'
      path: '/reader/$conversionId'
      fullPath: '/biblioteca/reader/$conversionId'
      preLoaderRoute: typeof BibliotecaReaderConversionIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/reader-chapter/$sourceId': {
      id: '/biblioteca/reader-chapter/$sourceId'
      path: '/reader-chapter/$sourceId'
      fullPath: '/biblioteca/reader-chapter/$sourceId'
      preLoaderRoute: typeof BibliotecaReaderChapterSourceIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/converter/$jobId': {
      id: '/biblioteca/converter/$jobId'
      path: '/converter/$jobId'
      fullPath: '/biblioteca/converter/$jobId'
      preLoaderRoute: typeof BibliotecaConverterJobIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaSourceIdRoute: typeof BibliotecaSourceIdRoute
  BibliotecaProgressoRoute: typeof BibliotecaProgressoRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  BibliotecaConverterJobIdRoute: typeof BibliotecaConverterJobIdRoute
  BibliotecaReaderChapterSourceIdRoute: typeof BibliotecaReaderChapterSourceIdRoute
  BibliotecaReaderConversionIdRoute: typeof BibliotecaReaderConversionIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaSourceIdRoute: BibliotecaSourceIdRoute,
  BibliotecaProgressoRoute: BibliotecaProgressoRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  BibliotecaConverterJobIdRoute: BibliotecaConverterJobIdRoute,
  BibliotecaReaderChapterSourceIdRoute: BibliotecaReaderChapterSourceIdRoute,
  BibliotecaReaderConversionIdRoute: BibliotecaReaderConversionIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FontesRoute: FontesRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  WizardRoute: WizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
